[workspace]
members = [
    "schemsearch-cli",
    "schemsearch-lib",
    "schemsearch_faster",
    "schemsearch-files",
    "schemsearch-sql",
    "schemsearch-java"
]

[profile.small]
inherits = "release"
lto = true
strip = true
opt-level = "z"
codegen-units = 1
