[package]
name = "schemsearch-files"
version = "0.1.2"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
flate2 = "1.0.25"
hematite-nbt = "0.5.2"
serde = "1.0.152"
serde_json = "1.0.84"

